services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: move-up
    environment:
      - API_PORT=3333
      - REACT_NATIVE_PACKAGER_HOSTNAME=<YOUR_IP>
    ports:
      - "3333:3333"
      - "8081:8081"
    volumes:
      - .:/app
    command: sh -c "exec ./run.sh"
    networks:
      - app-network
    stdin_open: true
    tty: true
networks:
  app-network:
    driver: bridge
